name: PipelineWorkflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  trigger-azure-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Azure DevOps Pipeline
        uses: azure/pipelines@v1
        with:
          azure-devops-project-url: 'https://dev.azure.com/ramansharma95/MyProjecct'
          azure-pipeline-name: 'Ascendion-raman'
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
